APPers/Controllers/MenuController.cs
using APPers.Data;
using APPers.Models.Menu;
using APPers.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace APPers.Controllers
{
    public class MenuController : Controller
    {


        // GET: Menu
        public ActionResult Index()
        {

            var service = CreateMenuService();
            var model = service.GetAllOrders();

            return View(model);
        }


        public ActionResult OrderHistory()
        {

            var service = CreateMenuService();
            var model = service.GetMenus();

            return View(model);
        }


        //GET
        public ActionResult Create()
        {

            var userId = Guid.Parse(User.Identity.GetUserId());

            List<Beer> Beers = new BeerService().GetBeersDropDown().ToList();
            ViewBag.BeerMenu = new BeerService().GetBeersDropDown().ToList();


            List<Beer> BeersInStock = new List<Beer>();
            foreach (Beer beer in Beers)
            {
                if (beer.InRotation == true)
                {
                    BeersInStock.Add(beer);
                }
            }

            //Beers.Select(b => new SelectListItem() { });
            var query = from b in BeersInStock
                        select new SelectListItem()
                        {
                            Value = b.BeerId.ToString(),
                            Text = b.BeerName + " $" + b.Price
                        };

            ViewBag.BeerId = query.ToList();


            //Generate Drop Down for Tabs
            List<Tab> Tabs = new TabService().GetTabsDropDown().ToList();

            List<Tab> OpenTabs = new List<Tab>();
            foreach (Tab tab in Tabs)
            {
                if (tab.OwnerId == userId)
                {
                    if (tab.TabPaid == false)
                    {
                        OpenTabs.Add(tab);
                    }
                }
            }


            var query2 = from t in OpenTabs
                             //.Where(e => e.OwnerId == userId)
                         select new SelectListItem()
                         {
                             Value = t.TabId.ToString(),
                             Text = t.Name,
                         };
            ViewBag.TabId = query2.ToList();

            return View();
        }

        //Add code here vvvv
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MenuCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = CreateMenuService();

            if (service.CreateMenu(model))
            {
                TempData["SaveResult"] = $"Your drink is on the way to the {model.Location} station!";
                return RedirectToAction("Index", "Home");
            };

            ModelState.AddModelError("", "Your drink could not be ordered.");

            return View(model);
        }

        private MenuService CreateMenuService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new MenuService(userId);
            return service;
        }

        public ActionResult Details(int id)
        {
            var svc = CreateMenuService();
            var model = svc.GetMenuById(id);




            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateMenuService();
            var detail = service.GetMenuById(id);

            List<Beer> Beers = new BeerService().GetBeersDropDown().ToList();
            List<Beer> BeersInStock = new List<Beer>();
            foreach (Beer beer in Beers)
            {
                if (beer.InRotation == true)
                {
                    BeersInStock.Add(beer);
                }
            }


            ViewBag.BeerId = BeersInStock.Select(b => new SelectListItem()
            {
                Value = b.BeerId.ToString(),
                Text = b.BeerName + " $" + b.Price,
                Selected = detail.BeerId == b.BeerId
            });

            //ViewBag.BeerId = query.ToList();

            List<Tab> Tabs = new TabService().GetTabsDropDown().ToList();

            List<Tab> OpenTabs = new List<Tab>();
            foreach (Tab tab in Tabs)
            {
                if (tab.TabPaid == false)
                {
                    OpenTabs.Add(tab);
                }
            }


            var query2 = from t in OpenTabs
                             //.Where(e => e.OwnerId == _userId)
                         select new SelectListItem()
                         {
                             Value = t.TabId.ToString(),
                             Text = t.Name,
                         };
            ViewBag.TabId = query2.ToList();


            var model =
                new MenuEdit
                {
                    OrderId = detail.OrderId,
                    TabId = detail.TabId,
                    Location = detail.Location,
                    BeerId = detail.BeerId,
                    OrderComplete = detail.OrderComplete,
                    OrderTotal = detail.OrderTotal,
                };
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MenuEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.OrderId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateMenuService();

            if (!service.UpdateMenu(model) && !service.UpdateKeys(model))
            {
                TempData["SaveResult"] = "Your order was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your order could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateMenuService();
            var model = svc.GetMenuById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateMenuService();

            service.DeleteMenu(id);

            TempData["SaveResult"] = "Your note was deleted";

            return RedirectToAction("Index");
        }

    }
}

APPers/Controllers/TabController.cs
using APPers.Data;
using APPers.Models.Menu;
using APPers.Models.Tab;
using APPers.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APPers.Controllers
{
    public class TabController : Controller
    {
        // GET: Tab
        public ActionResult Index()
        {

            var service = CreateTabService();
            var model = service.GetTabs();

            return View(model);
        }

        public ActionResult MyTabs()
        {

            var service = CreateTabService();
            var model = service.GetTabs();

            return View(model);
        }


        // GET: Tab
        public ActionResult TabsAdminView()
        {

            var service = CreateTabService();
            var model = service.GetTabsAdmin();

            return View(model);
        }



        //GET
        public ActionResult Create()
        {
            return View();
        }

        //Add code here vvvv
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TabCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = CreateTabService();

            if (service.CreateTab(model))
            {
                TempData["SaveResult"] = "Your tab was created!";
                return RedirectToAction("Index","Home");
            };

            ModelState.AddModelError("", "Tab could not be added.");

            return View(model);
        }

        private TabService CreateTabService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new TabService(userId);
            return service;
        }

        public ActionResult Details(int id)
        {
            var svc = CreateTabService();
            var model = svc.GetTabById(id);

            var allDetails = new MenuService().GetOrdersDropDown().ToList();

            List<MenuListItem> orderDetails = new List<MenuListItem>();
            foreach (MenuListItem menu in allDetails)
            {
                if (menu.TabId == id)
                {
                    orderDetails.Add(menu);
                }
            }

            ViewBag.OrderDetails = orderDetails;

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateTabService();
            var detail = service.GetTabById(id);
            var model =
                new TabEdit
                {
                    TabId = detail.TabId,
                    Name = detail.Name,
                    TabPaid = detail.TabPaid,
                    GrandTotal = detail.GrandTotal,
                   
                };


            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TabEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.TabId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateTabService();

            if (service.UpdateTab(model))
            {
                TempData["SaveResult"] = "Process complete, thanks for choosing APPers!!";
                return RedirectToAction("Index", "Home");
            };

            ModelState.AddModelError("", "There was an error, please try again.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateTabService();
            var model = svc.GetTabById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateTabService();

            service.DeleteTab(id);

            TempData["SaveResult"] = "Your note was deleted";

            return RedirectToAction("Index");
        }

    }
}

APPers/Views/Menu/Create.cshtml
@model APPers.Models.Menu.MenuCreate

@{
    ViewBag.Title = "APPers Menu";
}

<h2>APPers Menu</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <h4>Select From One Of The Beers Below:</h4>

        <h5>Haven't started a tab yet? <input type="button" class="btn btn-primary btn-secondary" value="Start Tab" onclick="location.href='@Url.Action("Create", "Tab")'" /> </h5>

        <hr />

        @foreach (APPers.Data.Beer item in ViewBag.BeerMenu)
        {
            if (item.InRotation == true)
            {

                <div class="col-md-4">
                   
                    <dl class="dl-horizontal">

                        <dt>
                            @Html.DisplayNameFor(modelItem => item.BeerName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(modelItem => item.BeerName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(modelItem => item.TypeOfBeer)
                        </dt>

                        <dd>
                            @Html.DisplayFor(modelItem => item.TypeOfBeer)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(modelItem => item.Price)
                        </dt>

                        <dd>
                            @Html.DisplayFor(modelItem => item.Price)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(modelItem => item.Description)
                        </dt>

                         @*This is for if I want to add pictures to each drink next to the menu items...*@ 
                            <dt style="height: 200px; align-content; margin: auto;" >
                            <img src="@Html.DisplayFor(modelItem => item.ImageURL)" style="background: none; opacity: 1.0; max-width: 100%; max-height: 100%;"/>
                        </dt>

                        <dd>
                            @Html.DisplayFor(modelItem => item.Description)
                        </dd>

                        


                    </dl>
                </div>
            }
        }
</div>

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="dl-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.TabId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.TabId, ViewBag.TabId as SelectList, "---Assign Tab---")
                    @Html.ValidationMessageFor(model => model.TabId, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BeerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.BeerId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.BeerId, ViewBag.BeerId as SelectList, "---Select Beer---")
                @Html.ValidationMessageFor(model => model.BeerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Location, "---Select Delivery Location---")
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary btn-secondary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancel", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

APPers/Views/Menu/Delete.cshtml
@model APPers.Models.Menu.MenuDetail

@{
    ViewBag.Title = "Delete Order";
}

<h2>Delete Order</h2>

<h3>Are you sure you want to delete this order?</h3>
<div>
    <h4>MenuDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BeerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BeerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BeerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BeerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderComplete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderComplete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedUtc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

APPers/Views/Menu/Details.cshtml
@model APPers.Models.Menu.MenuDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MenuDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TabName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TabName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BeerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BeerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderComplete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderComplete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedUtc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OrderId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

APPers/Views/Menu/Edit.cshtml
@model APPers.Models.Menu.MenuEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Order Edit</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.OrderId)

    <div class="form-group">
        @Html.LabelFor(model => model.TabId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.TabId, ViewBag.TabId as SelectList, new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.TabId, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.BeerId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.BeerId, ViewBag.BeerId as SelectList, new { @class = "text-danger" })
            @*@Html.EditorFor(model => model.BeerId, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.BeerId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrderComplete, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.OrderComplete)
                @Html.ValidationMessageFor(model => model.OrderComplete, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

APPers/Views/Menu/Index.cshtml
@model IEnumerable<APPers.Models.Menu.MenuListItem>

@{
    ViewBag.Title = "Index";
}

<h2>Open Orders</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in" role="alert">

        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TabName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BeerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderTotal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderComplete)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.OrderComplete == false)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TabName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BeerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderTotal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderComplete)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedUtc)
                </td>
                <td>
                    <input type="button" class="btn btn-primary  btn-sm" value="Complete/Edit" onclick="location.href='@Url.Action("Edit", new { id = item.OrderId })'" />
                </td>
                <td>
                    <input type="button" class="btn btn-primary  btn-sm" value="Details" onclick="location.href='@Url.Action("Details", new { id = item.OrderId })'" />
                </td>
                <td>
                    <input type="button" class="btn btn-primary  btn-sm" value="Cancel" onclick="location.href='@Url.Action("Delete", new { id = item.OrderId })'" />
                </td>
            </tr>
        }
    }

</table>

<hr />
<hr />

<h2>Past Orders</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TabName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BeerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderTotal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderComplete)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.OrderComplete == true)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TabName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BeerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderTotal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderComplete)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedUtc)
                </td>
                <td>
                    <input type="button" class="btn btn-primary  btn-sm" value="Edit" onclick="location.href='@Url.Action("Edit", new { id = item.OrderId })'" />
                </td>
                <td>
                    <input type="button" class="btn btn-primary  btn-sm" value="Details" onclick="location.href='@Url.Action("Details", new { id = item.OrderId })'" />
                </td>
                <td>
                    <input type="button" class="btn btn-primary  btn-sm" value="Cancel" onclick="location.href='@Url.Action("Delete", new { id = item.OrderId })'" />
                </td>
            </tr>
        }
    }

</table>

APPers/Views/Menu/OrderHistory.cshtml
@model IEnumerable<APPers.Models.Menu.MenuListItem>

@{
    ViewBag.Title = "My Orders";
}

<h2>My Order History</h2>

<p>
    <input type="button" class="btn btn-primary btn-secondary" value="Create New" onclick="location.href='@Url.Action("Create")'" />
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderId)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.TabId)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.TabName)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.BeerId)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.BeerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderTotal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderComplete)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.ModifiedUtc)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderId)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.TabId)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.TabName)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.BeerId)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.BeerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderTotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderComplete)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedUtc)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.ModifiedUtc)
                </td>*@
            <td>

                @if (item.OrderComplete == false)
                {
                <input type="button" class="btn btn-primary  btn-sm" value="Cancel Order" onclick="location.href='@Url.Action("Delete", new { id = item.OrderId })'" />}
            </td>


        </tr>
    }

</table>